export const CREATE_GAME = 'CREATE_GAME'
export const JOIN_GAME = 'JOIN_GAME'
export const LEAVE_GAME = 'LEAVE_GAME'
export const UPDATE_PLAYERS = 'UPDATE_PLAYERS'
export const START_GAME = 'START_GAME'
export const UPDATE_GAME = 'UPDATE_GAME'
export const UPDATE = 'UPDATE'
export const DISPLAY = 'DISPLAY'